"""Add category and quantity_changed to InventoryLog

Revision ID: b3bdbd1774cc
Revises: f42adf35030a
Create Date: 2025-05-02 01:14:06.667033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3bdbd1774cc'
down_revision = 'f42adf35030a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('quantity_changed', sa.Integer(), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('quantity_changed')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
