"""Added inventory and inventory_log models

Revision ID: f42adf35030a
Revises: b36d1b1a24e3
Create Date: 2025-05-02 00:59:29.199062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42adf35030a'
down_revision = 'b36d1b1a24e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('donated_items', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.drop_column('contact')
        batch_op.drop_column('amount_or_item')
        batch_op.drop_column('donation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('donation_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('amount_or_item', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('donated_items')
        batch_op.drop_column('amount')

    op.drop_table('inventory_logs')
    op.drop_table('inventory')
    # ### end Alembic commands ###
