"""Add orphan model

Revision ID: fccdf5872e00
Revises: fffde53a234c
Create Date: 2025-05-01 13:17:46.005511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fccdf5872e00'
down_revision = 'fffde53a234c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orphans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('health_status', sa.String(length=100), nullable=True),
    sa.Column('education_status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orphans')
    # ### end Alembic commands ###
